stages:
  - build
  - test

build:
  stage: build
  image: node:18
  cache:
    paths:
      - node_modules/
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  image: node:18
  cache:
    paths:
      - node_modules/
  variables:
    CI: "true"
  script:
    - npm install --legacy-peer-deps
    - npm test -- --watchAll=false --passWithNoTests --forceExit --transformIgnorePatterns="node_modules/(?!(react-leaflet|@react-leaflet|leaflet)/)"