// This is a placeholder test generated by Create React App.
// It currently looks for the text "learn react" which no longer exists in App.tsx,
// so this test will fail if you run `npm test`. It should be updated or replaced
// with tests that reflect what the app actually renders.
//
// To run tests: npm test
// Jest watches for file changes and re-runs automatically.
import React from 'react';
import { render, screen } from '@testing-library/react';
import App from './App';

// `test(description, fn)` defines a single test case.
// `render(<App />)` mounts the component into a virtual DOM.
// `screen.getByText(...)` searches the rendered output for matching text.
// `expect(...).toBeInTheDocument()` asserts that the element exists.
test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
