// This file is auto-generated by Create React App (CRA).
// The triple-slash directive below pulls in type definitions that CRA adds
// globally — things like knowing that `import logo from './logo.svg'` returns
// a string URL, or that `process.env.REACT_APP_*` variables exist.
// You rarely need to touch this file.
/// <reference types="react-scripts" />

// This tells TypeScript that importing a .css file is valid and gives back an
// object mapping class names to strings (used when CSS Modules are enabled).
// Without this, TypeScript would error on lines like: import styles from './App.css'
declare module '*.css' {
  const content: { [className: string]: string };
  export default content;
}
